/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeio_jni_Natives */

#ifndef _Included_nativeio_jni_Natives
#define _Included_nativeio_jni_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeio_jni_Natives
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeio_jni_Natives_init
  (JNIEnv *, jclass);

/*
 * Class:     nativeio_jni_Natives
 * Method:    loadContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeio_jni_Natives_loadContent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
